stages:
  - build


before_script:
  - chmod +x setup-build-env.sh
  - ./setup-build-env.sh


build_app:
  image: node:18
  stage: build
  tags:
    - docker
  script:
    - cd Web_App
    - node -v
    - npm -v
    - npm install
    - npm run build

build_hardware_component:
  image: ubuntu:latest
  stage: build
  tags:
    - docker
  script:
    - export PATH=$PATH:/root/bin
    - pwd
    - cd Arduino
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal

    


  