stages:
  - build

build_app:
  stage: build
  image: node:18
  script:
    - node -v
    - curl -L https://www.npmjs.com/install.sh | sh  #  install npm
    - npm -v  # Check if npm is installed after installation
    - npm install
    - npm run build




  